# Generated by Django 4.1.3 on 2023-04-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositorMst',
            fields=[
                ('cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'depositor_mst',
            },
        ),
        migrations.CreateModel(
            name='OfficeMst',
            fields=[
                ('cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'office_mst',
            },
        ),
        migrations.CreateModel(
            name='PaymentConditionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no_show', models.BooleanField(null=True)),
                ('customer_department_show', models.BooleanField(null=True)),
                ('mark_show', models.BooleanField(null=True)),
                ('created_dt', models.DateTimeField(null=True)),
                ('updated_dt', models.DateTimeField(null=True)),
                ('created_user_id', models.IntegerField(null=True)),
                ('updated_user_id', models.IntegerField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('depositor_cd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.depositormst')),
                ('office_cd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.officemst')),
            ],
            options={
                'db_table': 'payment_condition_registration',
            },
        ),
    ]
